#We will use Ubuntu for our image
FROM ubuntu:latest

LABEL maintainer = "troyseamusphillips@gmail.com"

#Copies over all files from current directory (/home/ubuntu/RetirementWebsite) to container
COPY . /RetirementWebsite

WORKDIR /RetirementWebsite

# Updating Ubuntu packages/adding wget
RUN apt-get update -y
RUN apt-get install wget -y
RUN apt-get install python3 -y
RUN apt-get install python3-pip -y
RUN apt-get install -y locales
RUN apt-get upgrade -y

# Installing necessary tools
RUN pip3 install numpy
RUN pip3 install pandas
RUN pip3 install xlrd
RUN pip3 install flask
RUN pip3 install awscli
RUN locale-gen en_US.UTF-8

ENV FLASK_APP = app.py

EXPOSE 80

CMD ["python3", "app.py"]